# Skill-Spec Template v1.2
# Fill in all sections marked with TODO
# Run: skillspec validate <name> --strict
#
# Features:
# - agentskills.io compatibility (https://agentskills.io/specification)
# - Anthropic skill-creator patterns (https://github.com/anthropics/skills)
# - Superpowers and SuperClaude patterns support

spec_version: "skill-spec/1.2"

# Meta configuration (optional)
_meta:
  content_language: "en"  # en | zh | auto
  mixed_language_strategy: "union"  # union | segment_detect | primary
  format: "full"  # full | minimal (minimal requires only: skill, inputs, decision_rules, output_contract, edge_cases)
  token_budget: 500  # Target word count for generated SKILL.md (frequent: <200, standard: <500)
  agentskills_compat: false  # v1.2: Enable agentskills.io compatibility mode
  # v1.2: Progressive disclosure settings (agentskills.io pattern)
  # progressive_disclosure:
  #   metadata_tokens: 100    # ~100 tokens for metadata loaded at startup
  #   instructions_tokens: 2000  # <5000 tokens for main instructions
  #   max_lines: 500          # <500 lines for SKILL.md

# ============================================================================
# CORE SECTIONS (8 required for full format, 5 for minimal)
# ============================================================================

# 1. Skill Metadata (required)
skill:
  name: "TODO-verb-object"  # kebab-case, 1-64 chars (agentskills.io compliant)
  version: "1.0.0"
  purpose: "TODO: Single sentence describing what this skill does (1-1024 chars)"
  owner: "TODO-team-name"

  # Classification
  category: "TODO-category"  # documentation | analysis | generation | transformation | validation | orchestration
  complexity: "standard"     # low | standard | advanced
  tools_required:            # Claude Code tools this skill needs
    - Read
    - Write
    # - Grep
    # - Glob
    # - Bash
    # - Task
    # - WebSearch
  personas:                  # Roles that benefit from this skill
    - developer
    # - technical-writer
    # - architect
    # - qa-specialist
    # - security-engineer

  # agentskills.io compatibility fields (optional)
  # license: "Apache-2.0"    # SPDX identifier or "LICENSE" to reference bundled file
  # compatibility: "Requires Python 3.9+"  # Environment requirements (max 500 chars)
  # allowed_tools:           # Pre-approved tools (experimental, space-delimited in SKILL.md)
  #   - Read
  #   - Write
  #   - Bash
  # metadata:                # Custom key-value properties
  #   author: "your-name"
  #   homepage: "https://example.com"

# 2. Triggers (recommended)
# When should AI activate this skill? Use "Use when..." style from Superpowers
triggers:
  use_when:
    - "TODO: Primary trigger condition"
    - "TODO: Secondary trigger condition"
    # Examples:
    # - "User requests README generation"
    # - "Codebase lacks documentation"
    # - "API changes require doc updates"
  do_not_use_when:
    - "TODO: When NOT to use this skill"
    # Examples:
    # - "Translating existing documentation"
    # - "Creating marketing content"

# 3. Inputs (Input Contract, required)
inputs:
  - name: TODO_input_name
    type: string  # string | number | boolean | object | array
    required: true
    constraints:
      - not_empty
      # - max_length: 500
      # - min_value: 0
      # - pattern: "^[a-z]+$"
    domain:
      type: any  # enum | range | pattern_set | boolean | any
      # values: ["option_a", "option_b"]  # for enum
      # min: 0  # for range
      # max: 100  # for range
    description: "TODO: Precise semantic definition"
    tags: []  # Optional: ["content:code", "content:config", "sensitive:pii"]

# 4. Preconditions (required for full format)
preconditions:
  - "TODO: What must be true before this skill runs"

# 5. Non-goals (required for full format)
non_goals:
  - "TODO: Explicitly state what is out of scope"
  - "Does not infer missing data"
  - "Does not call external APIs"

# 6. Boundaries (new in v1.1, recommended)
# Clear declaration of what this skill will and will not do (SuperClaude-style)
boundaries:
  will:
    - "TODO: Explicit capability 1"
    - "TODO: Explicit capability 2"
    # Examples:
    # - "Extract documentation from code comments"
    # - "Generate Markdown formatted output"
    # - "Support bilingual (zh/en) output"
  will_not:
    - "TODO: Explicit limitation 1"
    - "TODO: Explicit limitation 2"
    # Examples:
    # - "Translate existing documentation between languages"
    # - "Create marketing or sales content"
    # - "Infer undocumented behavior"

# 7. Decision Rules (Explicit logic, required)
decision_rules:
  _config:
    match_strategy: first_match  # first_match | priority | all_match
    conflict_resolution: error   # error | warn | first_wins

  rules:
    - id: rule_validation_fail
      priority: 10
      when: "is_empty(TODO_input_name)"
      then:
        status: error
        code: EMPTY_INPUT

    - id: rule_default
      priority: 0
      is_default: true
      when: true
      then:
        status: success
        path: default

# 8. Steps (Execution Flow, required for full format)
# Technical step-by-step execution
steps:
  - id: validate
    action: validate_input
    output: validated_input

  - id: process
    action: TODO_main_action
    output: result
    based_on: [validated_input]

  - id: render
    action: format_output
    based_on: [result]

# 9. Behavioral Flow (new in v1.1, optional alternative/supplement to steps)
# Higher-level behavioral phases (SuperClaude-style)
# Use this for AI guidance on HOW to approach the task
behavioral_flow:
  - phase: analyze
    description: "TODO: What happens in analysis phase"
    key_actions:
      - "TODO: Key action 1"
      - "TODO: Key action 2"
    # Example:
    # description: "Parse source content, identify structure"
    # key_actions:
    #   - "Detect programming language"
    #   - "Extract comments and docstrings"
    #   - "Identify API signatures"

  - phase: generate
    description: "TODO: What happens in generation phase"
    key_actions:
      - "TODO: Key action 1"

  - phase: validate
    description: "TODO: What happens in validation phase"
    key_actions:
      - "TODO: Key action 1"

# 10. Output Contract (required)
output_contract:
  format: json  # json | text | markdown | yaml
  schema:
    type: object
    required: [status]
    properties:
      status:
        enum: [success, error]
      result:
        type: object
      error_code:
        type: string

# 11. Failure Modes (required for full format)
failure_modes:
  - code: EMPTY_INPUT
    retryable: false
    description: "Input was empty or missing"

  - code: VALIDATION_ERROR
    retryable: false
    description: "Input failed validation"

  - code: TODO_FAILURE_CODE
    retryable: true
    description: "TODO: Describe when this failure occurs"

# ============================================================================
# COVERAGE SECTIONS (1 required)
# ============================================================================

# 12. Edge Cases (required)
edge_cases:
  - case: empty_input
    expected:
      status: error
      code: EMPTY_INPUT

  - case: TODO_edge_case
    expected:
      status: success
      # Describe expected behavior

# ============================================================================
# ANTI-PATTERNS SECTION (new in v1.1, recommended)
# ============================================================================

# 13. Anti-patterns and Rationalizations (Superpowers-style)
# Common mistakes AI might make and how to counter them
anti_patterns:
  # Common mistakes
  mistakes:
    - pattern: "TODO: Describe a common mistake"
      why_bad: "TODO: Why this is problematic"
      correct: "TODO: What to do instead"
    # Example:
    # - pattern: "Copying source code directly into documentation"
    #   why_bad: "Users need explanations, not code duplicates"
    #   correct: "Extract key information and describe in natural language"

  # Rationalizations AI might use to skip rules (Superpowers-style)
  rationalizations:
    - excuse: "TODO: Common excuse for skipping this skill"
      reality: "TODO: Why that excuse is wrong"
    # Examples:
    # - excuse: "This feature is too simple to document"
    #   reality: "Simple features are easiest to document; skipping creates debt"
    # - excuse: "I'll document it after the feature stabilizes"
    #   reality: "Documentation written alongside code stays accurate"
    # - excuse: "The code is self-documenting"
    #   reality: "Code explains HOW, not WHY or WHEN to use"

  # Red flags that indicate rule violations (Superpowers-style)
  red_flags:
    - "TODO: Warning sign that skill is being misused"
    # Examples:
    # - "Attempting to generate docs without source code"
    # - "Skipping the analysis phase"
    # - "Publishing generated docs without validation"

# ============================================================================
# CONTEXT SECTIONS (optional)
# ============================================================================

# 14. Context (Collaboration info)
context:
  works_with:
    - skill: TODO-related-skill
      reason: "TODO: Why these skills work together"

  prerequisites:
    - "TODO: What user needs to do first"

  scenarios:
    - name: "TODO-scenario-name"
      trigger: "TODO: What triggers this scenario"  # new in v1.1
      description: "TODO: Describe typical usage scenario"

# ============================================================================
# EXAMPLES (optional, recommended)
# ============================================================================

# 15. Examples
examples:
  - name: "Basic usage"
    scenario: "TODO: Describe the context/scenario"  # new in v1.1
    trigger: "TODO: How user triggers this"          # new in v1.1
    input:
      TODO_input_name: "example value"
    output:
      status: success
      result: {}
    explanation: "TODO: Explain what happens in this example"
